pipeline {
    agent {
        docker {
            image 'maven:3.5.3-jdk-10-slim'
        }
    }
    stages {
        stage('Maven version') {
            steps {
                sh 'mvn -v'
                sh 'java version'
            }
        }
    }
}